### PR TITLE
Ratings [P1]

### PR DESCRIPTION
**Pull request by samflab**
I have added the ratings. haven't updated the doc, only the component
image

Thank you

### CODE REVIEW

**Comment by JowelTisso** [comment]
The doc links are not working in the preview and no side navigation.

**Review by jeetsdev — APPROVED** [review]
Looks good

**Comment by samflab** [comment]
> The doc links are not working in the preview and no side navigation.

yeah, because some of the code is in the dev branch.

**Review by Ash-D23 — APPROVED** [review]
looks good, padding can be added

**Review by JowelTisso — APPROVED** [review]

**Pull request merged**
