### PR TITLE
Added Avatar Component [P0]

### PR DESCRIPTION
**Pull request by samflab**
If you want to check this out in codesandbox, please add "box" after github in the browser URL. The project will run in codesandbox. To check out the avatar, change the URL to /avatar/avatar.html 
eg: https://u2f15.csb.app/avatar/avatar.html
here's the look:
image

Please review my work, thank you so much! :)

### CODE REVIEW

**Comment by rutvikpumak** [comment]
Approved

**Comment by ScoobyDubeyDo** [comment]
Everything looks good but you can use the `object-fit` property on all the img tags for better alignment of the images.
Read about it here 
https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit

**Comment by samflab** [comment]
> Everything looks good but you can use the `object-fit` property on all the img tags for better alignment of the images. Read about it here https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit

Thanks, I forgot about this. I have made the changes, check it.

**Review by NtshVrm — APPROVED** [review]
Looks good👍

**Review by Tejs1 — COMMENTED** [review]
Hi, Your icons are not showing in usage, cause you have imported it in HTML.
you should import in css.
@import url("https://use.fontawesome.com/releases/v5.15.4/css/all.css");

image

**Pull request merged**
