### PR TITLE
Added Button Component [P0]

### PR DESCRIPTION
**Pull request by samflab**
Hey, please review this component. I have added most of the variants. Here's the look:
image

### CODE REVIEW

**Review by md-amir-gauhar — CHANGES_REQUESTED** [review]
It would be nice if you attach/embed the code snippets which will allow the users to know what classes need to be added to use the respective button.

**Comment by samflab** [comment]
> It would be nice if you attach/embed the code snippets which will allow the users to know what classes need to be added to use the respective button.

I will do this in the documentation website. For now, I am focused on making my components.

**Review by md-amir-gauhar — APPROVED** [review]
Got it:) Pretty neat

**Review by vp5h — APPROVED** [review]
The code looks great, Just deploy it, would be far easier to review

**Pull request merged**
