### PR TITLE
Added: Text and List Components [P1]

### PR DESCRIPTION
**Pull request by samflab**
Please review these 2 components.
Deployed at: https://deploy-preview-10--azure-ui.netlify.app/text/text.html (text utilities)
https://deploy-preview-10--azure-ui.netlify.app/list/list.html (list components)
image
image
thank you

### CODE REVIEW

**Review by Anish-JS — APPROVED** [review]
Looks good

**Review by ayush65 — APPROVED** [review]
Looks good👍

**Comment by rutvikpumak** [comment]
image
All the heading and paragraph looks same

**Review by NtshVrm — APPROVED** [review]

**Comment by samflab** [comment]
> image All the heading and paragraph looks same

fixed that ! :)

**Pull request merged**
